### PR TITLE
seed random generator in options

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by apacha** [comment]
Is adding that one field enough to achieve this behavior?

**Comment by rettinghaus** [comment]
Just from a brief look through the project, I assume it is. Testing is on your side.

**Comment by apacha** [comment]
Links: https://enotemusic.atlassian.net/browse/AD-583

**Comment by apacha** [comment]
Our manually defined IDs remain constant. Other IDs are assigned anew upon each import. I guess this behavior is fine, as we do not track objects that get newly assigned IDs, but this feature is only relevant for objects that already had IDs when they were created from the OMR pipeline.

**Pull request merged**
